"""create cart_items table

Revision ID: 7084e10ab75a
Revises: c6ac0202e0a0
Create Date: 2025-04-30 22:25:40.907813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7084e10ab75a'
down_revision = 'c6ac0202e0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    # ### end Alembic commands ###
