"""Fix image_data type and add genre enum

Revision ID: b69f6f2a0713
Revises: 7084e10ab75a
Create Date: 2025-04-30 22:48:47.967689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b69f6f2a0713'
down_revision = '7084e10ab75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', mysql.ENUM('Fiction', 'Non-Fiction', 'Fantasy', 'Science', 'Biography', 'Mystery', 'Romance', 'History'), nullable=True))
        batch_op.alter_column('image_data',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
